import {
  Baby,
  Briefcase,
  Camera,
  Car,
  ChefHat,
  Cog,
  Construction,
  Droplets,
  FileText,
  Hammer,
  Heart,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Megaphone,
  Music,
  Paintbrush,
  PenTool,
  Pill,
  BookOpen,
  Scale,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  Smartphone,
  Snowflake,
  Sparkles,
  Stethoscope,
  TreePine,
  Truck,
  Tv,
  UtensilsCrossed,
  Wrench,
  Zap,
  Ruler,
  type LucideIcon,
} from 'lucide-react';
import { resolveCategoryIconKey, type CategoryIconKey } from '@/lib/category-icon-keys';

const CATEGORY_ICON_COMPONENTS: Record<CategoryIconKey, LucideIcon> = {
  wrench: Wrench,
  hammer: Hammer,
  construction: Construction,
  ruler: Ruler,
  paintbrush: Paintbrush,
  lightbulb: Lightbulb,
  droplets: Droplets,
  snowflake: Snowflake,
  car: Car,
  truck: Truck,
  smartphone: Smartphone,
  tv: Tv,
  laptop: Laptop,
  'tree-pine': TreePine,
  leaf: Leaf,
  'chef-hat': ChefHat,
  'utensils-crossed': UtensilsCrossed,
  heart: Heart,
  baby: Baby,
  stethoscope: Stethoscope,
  pill: Pill,
  shield: Shield,
  lock: Lock,
  scale: Scale,
  'file-text': FileText,
  megaphone: Megaphone,
  'pen-tool': PenTool,
  'book-open': BookOpen,
  'shopping-bag': ShoppingBag,
  camera: Camera,
  music: Music,
  shirt: Shirt,
  sparkles: Sparkles,
  home: Home,
  settings: Settings,
  cog: Cog,
  bolt: Zap,
  briefcase: Briefcase,
};

export function resolveCategoryIcon(
  icon: string | null | undefined,
  slug: string | null | undefined
) {
  return CATEGORY_ICON_COMPONENTS[resolveCategoryIconKey(icon, slug)];
}
